### ISSUE TITLE
Define the power (import, export, ...) without decimal places

### ISSUE THREAD

**Issue by ToboliGermany** [a529987659852/openwbmqtt#18]
Hello,

Would it be possible to specify the power (import, export, ...) without any decimal digits.

![grafik](https://user-images.githubusercontent.com/91594568/153701289-f67c2fcf-30fa-478f-996d-0fadd7b68940.png)

![grafik](https://user-images.githubusercontent.com/91594568/153701162-e2049990-e825-48a3-992c-e53e45ed511e.png)

Super integration! Thank you for your effort.

Regards, Oliver

**Comment by a529987659852** [comment]
Hi Oliver,
You're correct: this is not nice. I'll correct this and also change the uom
to kWh.

Regards
Andreas

ToboliGermany ***@***.***> schrieb am Sa., 12. Feb. 2022,
08:16:
