### ISSUE TITLE
Sensors are all not provided

### ISSUE THREAD

**Issue by Nesie** [a529987659852/openwbmqtt#19]
Installed and configured everything like described, but got only >unknown< for the sensor values.
Have double checked the Enty in config/.storage/core.config_enties:

        {
            "entry_id": "7c5ef5fa3fa3b69a3c36350f0b4a832e",
            "version": 1,
            "domain": "openwbmqtt",
            "title": "openWB/",
            "data": {
                "mqttroot": "openWB/",
                "chargepoints": 1,
                "host": "192.168.178.52"
            },
            "options": {},
            "pref_disable_new_entities": false,
            "pref_disable_polling": false,
            "source": "user",
            "unique_id": "openWB/",
            "disabled_by": null
        }
which should be correct.

And I got all the MQTT values if I use an client (MQTT Fx) and subscribe to openWB/#
but not in the integraten !??

I’m a little bit lost now. Maybe you have a hint for me that  can help.

**Comment by a529987659852** [comment]
Try the mqttroot without / at the end (openWB only)



Nesie ***@***.***> schrieb am Fr., 11. März 2022, 18:14:

**Comment by Nesie** [comment]
Thanks a lot, yes the / was to much. Sometimes you have to have a second pair of eyes.
