### ISSUE TITLE
sensor.openwb_energie_erzeugt_haus not used any more

### ISSUE THREAD

**Issue by KoljaHenckel** [a529987659852/openwbmqtt#21]
Hi! 
I really like your addon!
I have set up my openWB and integrated the values into HomeAssistant quite nice!
Also the connections back from Homeassistant to OpeWB work well (like changing Charging parameters etc).

I recently noticed that some sensors are not filled with data any more:
sensor.openwb_energie_erzeugt_haus
sensor.openwb_energie_export_haus
sensor.openwb_energie_import_haus
sensor.openwb_cp1_geladene_energie
sensor.openwb_cp2_geladene_energie

in MQTT, these values are sill there:
![Bildschirmfoto 2022-03-28 um 12 33 18](https://user-images.githubusercontent.com/23027041/160380149-94201163-39af-4458-906d-61ee049358d2.png)
(e.g.)

I am currently using openwb 1.9.259 beta

**Comment by a529987659852** [comment]
Hi Kolja,
I renamed the labels of some sensors for better understandability. Unfortunately, this means that some sensors are now available under a new name.
Old -> new can be found here (scroll down to const.py)
https://github.com/a529987659852/openwbmqtt/commit/224404c53fc08df867b05e273d72abb20b95ec8a

You can either manually remove the old sensors and use the new ones instead. Or just remove and re-install the component.
Sorry for the inconvenience
Andreas
