### ISSUE TITLE
update integration to allow the usage within the energy dashboard

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#24]
Hi, I love the new energy dashboard from home assistant - and I would really appreciate the fact, if openwbmqtt could be integrated there.
Unfortunately, It seems, that the sensors don't meet the requirements to be shown in the energy dashboard, since it is not available in the configuration area of the dashboard.

It would probably make sense to add the ev-charger as a battery type, as long as there isn't a dedicated configuration for electric vehicles available.
Can you consider to implement the integration into the HA Energy Dashboard (without the need to create utility_meters and so on manually)

Thanks :)

**Comment by ChristophCaina** [comment]
thanks for the update :)
I think, this might add some benefits for the users (who might not have their own PV integration or lost the ability to monitor their PV in homeassistant directly 👍

**Comment by ChristophCaina** [comment]
Hi @a529987659852 :

During the last days I've noticed the following behave of the sensor: "total_charging" - which should be changed for the energy dashboard:

1. I've charged aprox 15 kWh to my car.
--> Everything was shown as expected within the energy dashboard.
2. after I've unplugged the car, the sensor switcht to "0.00" which isn't expected by the energy dashboard.
--> therefore, it recalculated the complete graph and caused a mess in the statistics.
3. today, after I've plugged in my car again, the sensor came back with the previous amount of charged kWh.

The energy Dashboard requires a continues grow of the sensor values.
It should not fall back to 0.00 kWh - otherwise, it will re-add the previous sensor state (15 kWh) the next time:

statistics would be like that:

hh:mm    value          total
11:00      0.0             0.0
12:00      5.5             5.5
13:00      4.5             10.0
14:00      5.0             15.0
15:00      0.0             15.0
16:00      0.0             15.0
--------
10:00     15.0             30.0
11:00       4.3             34.3
12:00       5.0             39.3

and so on.
Is it possible to fix the sensor to keep it's value even if the car will be unplugged?

**Comment by a529987659852** [comment]
Update: Most other wallboxes and inverters use total_increasing for such kind of sensors - I'll try that as well.

**Comment by ChristophCaina** [comment]
hi, just as mentioned above, I wanted to provide an update to the sensor:

![grafik](https://user-images.githubusercontent.com/26391061/173770039-d6f1474f-ecd0-4b26-9d40-a06a912168ae.png)
it seems, that now, the sensor has resetted the last charging - and felt back to the 14,8 kWh which I have manually repaired in the statistics.

The cable is still plugged in, but not locked - I did an update on homeassistant, so the system did reinitiate the sensors
