### ISSUE TITLE
settings made in HomeAssistant does not change

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#26]
Hi,
I've created a small Dashboard for the openWB in HomeAssistant, where I've also used some of the items which "should" (?) change settings on the Device.

![grafik](https://user-images.githubusercontent.com/26391061/171597844-e43ed406-933b-464a-a915-6df798a711e7.png)

Now, I've noticed, the following:

1. I have changed the setting for "Mindestladestrom" to 6A on the Wallbox.
It was previously on 10A

- The setting will not be reflected in HomeAssistant.

2. When I change the setting in HomeAssistant to 6A it will change back to 10A after restarting HomeAssistant.

**Comment by ChristophCaina** [comment]
I have observed this a bit more.

- When I change the settings in OpenWB - it will immediately applied and visible in HomeAssistant.
- If I restart HomeAssistant, the settings will be reset, althought they are still as they have been set within the openWB.

This applies to:
"SoC Begrenzung" - which has been set to 80%
"Mindestladestrom" - which has been set to 6A
and pretty sure also for the others, which I haven't changed / tested yet.

**Comment by ChristophCaina** [comment]
I did some more tests on that issue:

1. Changes applied in openWB were visible in HomeAssistant (as mentioned in comment 2.
2. After rebooting HomeAssistant, these changes were reset in HomeAssistant
3. After rebooting openWB the changed values were persistant in HomeAssistant
4. Changing the settings in HomeAssistant does change the settings in openWB
5. After rebooting HomeAssistant, the changes were reset in HomeAssistant again
6. After -reopen the openWB settings, the changes made in HomeAssistant were not persistant.

-- it requires a reboot of the openWB to "apply" the changes (without reboot, they are fix in openWB but HomeAssistant will always show the old settings)
-- HomeAssistant can change the settings on the openWB but does not save them.

**Comment by ChristophCaina** [comment]
maybe, the better question:

- what is the reason / benefit of having number / select fields, if the state won't be applied by the openWB?
Switching between Min+PV and PV through the integration did not change the behave of the openWB ... I had to switch it directly on the openwb itself.... ?!

**Comment by a529987659852** [comment]
Found the root cause: Posted to the wrong MQTT topics.
I'm currently solving this issue and post an update.
