### ISSUE TITLE
How will 'time remaing' be calculated?

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#30]
I've noticed that the remaining charging time does Not match the Information for the remaining time provided by the Car.

The Sensor from the openWB Provides an UTC timestamp, which I have converted Into a netter readable local timestamp.

Here's what the Integration does estimate:
![Screenshot_20220617-090155](https://user-images.githubusercontent.com/26391061/174246362-609eec27-df21-405d-998f-bbb8af98ff6d.png)

While the Integration from the Car Provides an estimation of nearly 4 hours:
![Screenshot_20220617-090112](https://user-images.githubusercontent.com/26391061/174246584-73a4c34e-cb46-4d26-8b8f-4760712cf5a5.png)

**Comment by riesi77** [comment]
Does OpenWB display correctly? Maybe you need to adjust the battery: In OpenWB go to Einstellungen - Allgemein, Chapter EV Daten - Akkugröße in kWh.

**Comment by ChristophCaina** [comment]
this is an issue with openWB especially when charing will be done via solar...
ticket can be closed :)
