### ISSUE TITLE
feature request: priorityModeEVBattery value

### ISSUE THREAD

**Issue by RaidObServer** [a529987659852/openwbmqtt#40]
Hi Andreas,

thank you very much for this great openwb integration, works perfect.
I have one question: Is it possible to add the priorityModeEVBattery value to switch between EV and Storage in PV mode?

openWB Topic: openWB/config/get/pv/priorityModeEVBattery

best regards & many thanks
Stefan

**Comment by ChristophCaina** [comment]
Hi, it would probably be possible to get the state, but probably it's Not possible to Set the Switch - If there's No /set/ topic

**Comment by a529987659852** [comment]
Hi Stefan and Christoph,
I can include this as a dropdown. 
However, as Christoph mentioned, I need to know the respective SET topic.

According to https://github.com/snaptec/openWB/blob/58e8d9f802c7c1c4e004a3f705f0304b9b1a8f48/runs/mqttsub.py --> Line 1040-1045, this should be openWB/config/set/pv/priorityModeEVBattery 0 or 1. 

Could you please verify this by logging into the MQTT server of the openWB and change the setting from the UI (I cannot test this at the moment).

Thanks
Andreas

**Comment by RaidObServer** [comment]
Hi Andreas and Christoph,

thank you very much for the fast replay.
The settopic for this command is exactly the same as in the link:

openWB/config/set/pv/priorityModeEVBattery

value: 0 = Storage (Speicher in german)
value: 1 = EV 

I published the topic with the values in the mqtt-explorer and in the GUI i see the changes.

best regards & thanks
Stefan

**Comment by a529987659852** [comment]
Hi Stefan,
should be implemented with commit 70d873e and version 0.5.7.
Please test and close this FR if everything works as expected.

Guten Rutsch!
Andreas

**Comment by RaidObServer** [comment]
Hi Andreas,

Thanks for the quick implementation, works as expected.
Do you have a paypal account, I would like to buy you a beer?

Guten Rutsch und nochmals vielen Dank.
Stefan

**Comment by RaidObServer** [comment]
Hi Andreas,

Thanks for the quick implementation, works as expected.
Do you have a paypal account, I would like to buy you a beer?

Guten Rutsch und nochmals vielen Dank.
Stefan

**Comment by a529987659852** [comment]
Hi Sefan,
danke, aber keine Einladung erforderlich.
Wenn du mich einladen magst, spende den Wert des Biers an eine
gemeinnützige Organisation deines Vertrauens.

Gruß
Andreas

Am Sa., 31. Dez. 2022 um 14:39 Uhr schrieb RaidObServer <
***@***.***>:
