### ISSUE TITLE
OpenWB hide entities 

### ISSUE THREAD

**Issue by Chris383838** [a529987659852/openwbmqtt#47]
Hi,

how I can show hidden entities for example the battery parameters?
Thank you
![OpenWB](https://user-images.githubusercontent.com/22688323/225827594-a31fbe8b-70fb-498d-9722-e6d22e1588ac.png)

**Comment by Chris383838** [comment]
Danke, bin noch Anfaenger. Komme von Fhem :-).

**Comment by ChristophCaina** [comment]
> Komme von Fhem :-)
Das macht nichts ;)

**Comment by ChristophCaina** [comment]
#close
