### ISSUE TITLE
change the icon for 'sensor.openwb_heutiger_strom_export_kwh'

### ISSUE THREAD

**Issue by CodingRainer** [a529987659852/openwbmqtt#49]
the icon for the sensor 'sensor.openwb_heutiger_strom_export_kwh' should be 'mdi:transmission-tower-import'

**Comment by ChristophCaina** [comment]
You probably mean "heutiger_strom_bezug_kwh"

```
openwbSensorEntityDescription(
        key="evu/DailyYieldImportKwh",
        name="Heutiger Strom-Bezug (kWh)",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x), 2),
old:        icon="mdi:transmission-tower-export",
new:        icon="mdi:transmission-tower-import",
```

fixed and created PR #50

**Comment by ChristophCaina** [comment]
hm... just noticed, that the icon description is a bit misleading... ^^
![grafik](https://user-images.githubusercontent.com/26391061/229277858-f64825a5-194e-4757-b46d-003bb50d7ecd.png)

this would be valid for all sensors:
![grafik](https://user-images.githubusercontent.com/26391061/229277887-a60c156f-33cc-4344-9eea-ea27cd1d21cf.png)

Sorry - I'll change that again

**Comment by ChristophCaina** [comment]
should now be changed for all sensors in PR #51
