### ISSUE TITLE
OpenWB in HACS

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#6]
Hi,
I'm very Interessed to use this Integration in my homeassistant.
But I would really Like to See it available in HACS which is an Management System for Integrations (with Update Management, etc)

Would you consider this?

**Comment by a529987659852** [comment]
Hi Christoph,

I'm considering this. However, since I don't use HACS myself, I need to do some research how this would be done.
Andreas

**Comment by a529987659852** [comment]
Hi Christoph,
I tried this today and was able to add this integration via HACS. You have to add this repository as custom repo to HACS. At least in my case, I was successful.
Let me know if you have any issues.

**Comment by a529987659852** [comment]
Hi Christoph,
I tried this today and was able to add this integration via HACS. You have
to add this repository as custom repo to HACS. At least in my case, I was
successful.
Let me know if you have any issues.

Am Do., 16. Sept. 2021 um 23:38 Uhr schrieb Christoph <
***@***.***>:
