### ISSUE TITLE
When will openwbmqtt support openWB V2.0 firmware?

### ISSUE THREAD

**Issue by wolfirr** [a529987659852/openwbmqtt#66]
used openwbmqtt since several months and was not aware, that it is only compatible with versions up to 1.9. Updated openWB to V2.0, because I have an installation that has 2 WB, one on 32A and one at 16A, which you can not configure on V1.9 as a combined Master / Slave.
Are you planning to have a version supporting V2.0?

**Comment by a529987659852** [comment]
https://github.com/a529987659852/openwb2mqtt

SN173-109 Wolfgang Rank ***@***.***> schrieb am Fr., 23. Feb.
2024, 01:26:

**Comment by wolfirr** [comment]
Sorry, did not find that. Thank you very much
