### ISSUE TITLE
Question: Eqivalent to 1.9's "heutiger_hausverbrauch_kwh"

### ISSUE THREAD

**Issue by freakadings** [a529987659852/openwbmqtt#70]
First of all: 
Thank you so much for your work, i very much love having all the openWB values within home assistant!

Yesterday I upgraded my openWB from 1.9.3 to 2.1.4,
today some of my calculations within HASS did not work anymore i noticed that the 1.9's  "sensor.openwb_heutiger_hausverbrauch_kwh" wasn't present any longer (of course), but it seems i could not find a equivalent within the new version, neither within Home Assistant nor via the mqtt explorer.

Only thing i found was 
"openWB->counter->set->daily_yield_home_consumption = 8329.0" 
but it's way off from the correct value and I couldn't spot it within HASS.
However it would be somehow correct if i subtract the value 
"openWB->chargepoint->get->daily_imported = 4759.0" 

Am I missing something or is there no alternative?

Best regards 
Merlin

**Comment by ChristophCaina** [comment]
If you upgraded the openWB to an 2.x Software, you should probably go with the OpenWB2 integration
https://github.com/a529987659852/openwb2mqtt

**Comment by freakadings** [comment]
Sorry, i forgot to mention that i upgraded the integration already.

**Comment by ChristophCaina** [comment]
then you should probably raise a ticket in the github of the new integration ;)

**Comment by freakadings** [comment]
But if the wallbox doesn't provide the mqtt topic, how should the integration deliver it?

**Comment by freakadings** [comment]
Sorry, you're right never mind :D

**Comment by freakadings** [comment]
Sorry, you're right never mind :D
